/* automatically generated by rust-bindgen 0.71.1 */

pub type wchar_t = ::std::os::raw::c_ushort;
pub type max_align_t = f64;
pub type core_file = ::std::os::raw::c_void;
unsafe extern "C" {
    pub fn core_fread(
        file: *mut core_file,
        buffer: *mut ::std::os::raw::c_void,
        size: usize,
    ) -> usize;
}
unsafe extern "C" {
    pub fn core_fseek(
        file: *mut core_file,
        offset: usize,
        origin: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn core_fopen(filename: *const ::std::os::raw::c_char) -> *mut core_file;
}
unsafe extern "C" {
    pub fn core_fclose(file: *mut core_file);
}
